### ISSUE TITLE
run bug

### ISSUE THREAD

**Issue by 3071776** [chenwr727/SubErase-Translate-Embed#1]
Traceback (most recent call last):
  File "/root/SubErase-Translate-Embed/main.py", line 7, in <module>
    from modules.erase import remove_subtitles
  File "/root/SubErase-Translate-Embed/modules/erase.py", line 11, in <module>
    from modules.sttn import build_sttn_model, inpaint_video_with_builded_sttn
  File "/root/SubErase-Translate-Embed/modules/sttn.py", line 12, in <module>
    from STTN.core.utils import Stack, ToTorchFormatTensor
ModuleNotFoundError: No module named 'STTN.core'

**Comment by chenwr727** [comment]
cd SubErase-Translate-Embed
git clone https://github.com/researchmm/STTN.git`
